<?php

namespace AggregateIt\Admin;

use AggregateIt\Settings;

defined( 'ABSPATH' ) || exit;

/**
 * Shows the original source text, source citations, and any flagged invented figures on
 * the editor for generated posts — the "what did the AI change" view.
 */
final class PostMetaBox {

	public function __construct( private Settings $settings ) {}

	public function register(): void {
		add_action( 'add_meta_boxes', [ $this, 'add' ] );
	}

	public function add(): void {
		add_meta_box(
			'aggregate-it-source',
			__( 'Aggregate It — source', 'aggregate-it' ),
			[ $this, 'render' ],
			$this->settings->target_post_type(),
			'normal',
			'default'
		);
	}

	public function render( \WP_Post $post ): void {
		$cluster_id = get_post_meta( $post->ID, '_ai_cluster_id', true );
		if ( ! $cluster_id ) {
			echo '<p>' . esc_html__( 'Not generated by Aggregate It.', 'aggregate-it' ) . '</p>';
			return;
		}

		$original = (string) get_post_meta( $post->ID, '_ai_original', true );
		$urls     = (array) get_post_meta( $post->ID, '_ai_source_urls', true );
		$invented = (array) get_post_meta( $post->ID, '_ai_invented', true );

		echo '<p><strong>' . esc_html__( 'Cluster:', 'aggregate-it' ) . '</strong> #' . (int) $cluster_id . '</p>';

		if ( $urls ) {
			echo '<p><strong>' . esc_html__( 'Sources:', 'aggregate-it' ) . '</strong></p><ul>';
			foreach ( $urls as $url ) {
				echo '<li><a href="' . esc_url( $url ) . '" target="_blank" rel="noopener noreferrer">' . esc_html( $url ) . '</a></li>';
			}
			echo '</ul>';
		}

		if ( $invented ) {
			echo '<p style="color:#b91c1c"><strong>' . esc_html__( 'Possible invented figures:', 'aggregate-it' ) . '</strong> ' . esc_html( implode( ', ', $invented ) ) . '</p>';
		}

		echo '<p><strong>' . esc_html__( 'Original source text:', 'aggregate-it' ) . '</strong></p>';
		echo '<textarea readonly rows="10" style="width:100%;font-family:monospace;font-size:12px;">' . esc_textarea( $original ) . '</textarea>';
	}
}
